version: 2

defaults: &defaults
  docker:
  - image: deliveroo/circleci:0.2.2

remote_docker: &remote_docker
  docker_layer_caching: true
  reusable: true
  version: 17.09.0-ce

import_image: &import_image
  name: Import Docker image
  command: |
    set -ex
    docker load --input "workspace/${CIRCLE_PROJECT_REPONAME}-${CIRCLE_SHA1}.tar"

jobs:
  build:
    <<: *defaults

    steps:
    - setup_remote_docker:
        <<: *remote_docker

    - checkout

    - run:
        name: Build CI Image
        command: |
          docker build -f Dockerfile -t "${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}" .

    - run:
        name: Save CI Image
        command: |
          mkdir -p workspace
          docker save "${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}" \
              --output "workspace/${CIRCLE_PROJECT_REPONAME}-${CIRCLE_SHA1}.tar"

    - persist_to_workspace:
        root: workspace
        paths:
        - "*.tar"

  push_master:
    <<: *defaults
    steps:
    - add_ssh_keys:
        fingerprints:
          # Stored in 1password Team:SETI vault `id_rsa_circleci_circleci`
          - "5e:7e:b1:3a:b0:65:dc:7c:07:52:fd:dd:a2:87:02:fc"

    - setup_remote_docker:
        <<: *remote_docker

    - checkout

    - attach_workspace:
        at: workspace

    - run:
        <<: *import_image

    - run:
        name: Tag the git commit
        command: |
          # This fails if the tag already exists
          # preventing a push to the docker hub.
          git tag "$(cat VERSION)"
          git push --tags

    - run:
        name: Log in to Docker repository
        command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}

    - run:
        name: Push the image
        command: docker push $(./image)

  push_staging:
    <<: *defaults
    steps:
    - add_ssh_keys:
        fingerprints:
          # Stored in 1password Team:SETI vault `id_rsa_circleci_circleci`
          - "5e:7e:b1:3a:b0:65:dc:7c:07:52:fd:dd:a2:87:02:fc"

    - setup_remote_docker:
        <<: *remote_docker

    - checkout

    - attach_workspace:
        at: workspace

    - run:
        <<: *import_image

    - run:
        name: Log in to Docker repository
        command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}

    - run:
        name: Push the image
        command: docker push $(./image):staging

master_only: &master_only
  filters:
    branches:
      only:
      - master

staging_only: &staging_only
  filters:
    branches:
      only:
      - staging

workflows:
  version: 2

  build_and_push:
    jobs:
      - build

      - push_master:
          <<: *master_only
          requires:
          - build

      - push_staging:
          <<: *staging_only
          requires:
          - build
